version: '3.8'

services:
  web:
    build: .
    command: sh -c "/app/entrypoint.sh"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      - "3300:3300" # port for debugging
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PORT=8000
      - PYTHONUNBUFFERED=1
      
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres_data:
